# Generated by Django 3.1.5 on 2021-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20210202_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_wishers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
