# Generated by Django 3.1.5 on 2021-02-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20210208_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='utilizator',
            new_name='user',
        ),
    ]
