# Generated by Django 3.1.5 on 2021-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20210215_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
